### ISSUE TITLE
Continuing the discussion mirrored from where

### ISSUE THREAD

**Issue by mwpowellhtx** [gibbed/NDesk.Options#1]
[Concerning the question](/gibbed/Gibbed.BorderlandsOz/issues/23), mirrored from where? Not [Github](https://github.com/), I gather?

**Comment by gibbed** [comment]
From the original website: http://www.ndesk.org/Options

**Comment by mwpowellhtx** [comment]
Hmm, interesting. Well, it appears as though the any hints of the original repository have vanished. Thanks anyway for the feedback.

**Comment by gibbed** [comment]
Yeah, the project itself is pretty old. It might be worth thinking to rewrite/start a new Options parser with the updates C# has gotten over the years since.

**Comment by mwpowellhtx** [comment]
@gibbed Stay tuned... ;-)
